            - name: Push Docker Image
  # You may pin to the exact commit or the version.
  # uses: julioarruda/pushimagetoregistry@3679a680bb9d6cbf3c1de8aeed592faf1e140c8b
  uses: julioarruda/pushimagetoregistry@v1
  with:
    # Username Name with push permission
    acr-tokenname: 
    # Token/PWD with push permission
    acr-token: 
    # Docker Account Name
    acr-account: 
    # Docker Image Name
    acr-imagename: 
          
