name: Docker Image CI XT_VOX_AI 
push: ["container Repository]"
branches: [ "main1"] 
pull_request: 
branches: [ "main1"] 
jobs: 
build-and-push: 
runs-on: ubuntu-latest 
steps: 

name: Push the Docker image 
run: docker push ghcr.io/xyloite-dev/xt_vox_python:${{ env.BUILD_NUMBER }}
