            - name: Pull Request Package Labeler
  # You may pin to the exact commit or the version.
  # uses: csi-lk/package-labeler@9d0690f14094b67545af97aeb3d1140e6ba1283a
  uses: csi-lk/package-labeler@v1.0.1
  with:
    # The GITHUB_TOKEN secret
    repo-token: # optional
    # What subfolder should the script run within
    workspace: # optional, default is packages
    # The prefix to use for the labels
    prefix: # optional, default is pkg: 
          
